# docker-compose.yml

#version: '3.8'

services:
  public:
    build:
      context: .
      dockerfile: /Users/tatiananiauronis/Documents/CSC8567/CSC8567-Projets/django-site/Dockerfile.front
    # ports:
    #   - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    # ports:
    #   - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tniauronis
      POSTGRES_USER: tniauronis
      POSTGRES_PASSWORD: azerty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tniauronis"]  
      interval: 10s  
      timeout: 5s    
      retries: 5 

  nginx:
    image: nginx:latest
    volumes:
      - ./projet/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - public
      - api

volumes:
  postgres_data:
